---
format_version: 10
pipelines:
  selenium_tests:
    group: cicd_task_group
    lock_behaviour: unlockWhenFinished
    label_template:
    materials:
      git_selenium_tests:
        git: https://github.com/rolandsjlociks/cicd_task.git
        branch: main 
        shallow_clone: true
        auto_update: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - echo "Building Maven"


